language: python
python:
  - "2.7"
# Install dependencies
install:
  - "pip install nose"
  - "pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl"
# Run tests
script: nosetests