language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
# Install dependencies
install:
  # Add missing libc
  - cd /tmp
  - wget http://launchpadlibrarian.net/137699828/libc6_2.17-0ubuntu5_amd64.deb
  - sudo dpkg -i libc6_2.17-0ubuntu5_amd64.deb
  - cd -
  # Update compiler versions
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  # Install pip dependencies
  - pip install nose
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
# Run tests
script: nosetests